server:
  port: 8086

wechat:
  mini: {
    PLATFORM: {
      appid: 123,
      secret: abc
    },
    MINI_B: {
      appid: 456,
      secret: ddd
    },
    MINI_C: {
      appid: 789,
      secret: aaa
    }
  }
  crop:
    cropid: 123456789
    apps: {
      BOOK: {
        agentid: 1357,
        secret: abcdefg
      }
    }

person:
  name: ${random.uuid}
  email: 897735152@qq.com
  age: 23
  boss: false
  birthday: 2017.12.23
  maps: {k1: v1, k2: v2}
  list:
    - zhangsan
    - lisi
    - wangwu
  dog:
    name: 花花
    age: 3
logging:
  file: logs/platform.log


#debug: true