server:
  port: 8082

logging:
  file: logs/platform.log
    max-size: 10M
  level: info

spring:
  application:
    name: spring-boot-demo-jar
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc://mysql://localhost:3306/wechat
    username: root
    password: pass4mysql


person:
  name: ${random.uuid}
  email: 897735152@qq.com
  age: 23
  boss: false
  birthday: 2017.12.23
  maps: {k1: v1, k2: v2}
  list:
    - zhangsan
    - lisi
    - wangwu
  dog:
    name: 花花
    age: 3




#debug: true